### ISSUE TITLE
Too many files: limit the number of allowed files in queue, clear queue if it

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#112]
We want to actively discourage uploading huge numbers of files, but limiting the queue to 200. however we are concerned that we never let someone unknowingly upload 200 out of the 250 that tried to upload without knowing 50 were missing.

so, if the Queue Length ever hits 200, cancel all uploads, clear the queue and show an error message.

There is a tricky case with drag/drop as the files are added individually and suffer from a recent change in Chrome that are paging the results by 100 at a time.

Some parts of this work are done, but need review and completion of the drag/drop case.

**Comment by jonathancrispino** [comment]
Tried to upload a folder of 12,000 files - was told to retry as a zip.
