### ISSUE TITLE
Fix built in paging handling

### ISSUE THREAD

**Issue by kyle-kilmer** [NYPTI/DEMS#128]
If a folder has enough files in it, the UI automatically adds pagination controls.  But if the user clicks to see another page, they get an error and can not get to it.

**Comment by kyle-kilmer** [comment]
@andylippitt I don't have a good test case. I think we can just deploy this one and test in prod.

**Comment by jonathancrispino** [comment]
Tested with 550+ files in a case.  Works, but gets laggy with that many files showing.
