### ISSUE TITLE
NDS - Share folder didn't work

### ISSUE THREAD

**Issue by kyle-kilmer** [NYPTI/DEMS#149]
Steps to reproduce:
1 - Created NDS recipient
2 - Opened separate Browser window (different browser) as NDS recipient to test with
3 - Selected 'Share with recipient' on a folder, appears properly in DEMS
4 - Checked in other browser, didn't appear in NDS window
5 - Selected 'Share with recipient' on a single file, appears properly in DEMS
6 - Checked in other browser, single file appeared properly, folder still didn't appear
https://pcms.test.nypti.org/Defendant/18683965/Attachment/Index

**Comment by kyle-kilmer** [comment]
![image](https://user-images.githubusercontent.com/33431226/77548130-7f60a500-6e84-11ea-90c0-8f192aec6737.png)

**Comment by andylippitt** [comment]
This seems to be related to the security set on the files during LEO Upload. Will remedy, but if you'd like to keep testing the folder stuff, share non-leo folders/files.

**Comment by andylippitt** [comment]
you'll need to recreate any NDS recipients prior to the latest build to see the fix.
