### ISSUE TITLE
PDF Files Not Displaying

### ISSUE THREAD

**Issue by jonathancrispino** [NYPTI/DEMS#159]
1. Opened an existing sample case in PCMS-Test (Chrome, Windows).  Went to Discovery & Digital Files.  Found 2 issues.  Both are repeatable but cannot figure out what causes the difference in behavior.

     a. Opened a PDF file, and preview returns "unexpected server response" and does not show the document.
![image](https://user-images.githubusercontent.com/33261775/87971332-2bad4380-ca93-11ea-9635-874a5c6a24cb.png)

     b. Trying top open a PDF redirects to the file upload screen with an error toaster
![image](https://user-images.githubusercontent.com/33261775/87971413-4aabd580-ca93-11ea-8772-c5435ed0a1f3.png)

2. URL: https://pcms.test.nypti.org/Defendant/18683977/Attachment/Index, 
    Component - PDF Viewer

**Comment by gwendelen** [comment]
3.28.19-react
