### ISSUE TITLE
form ocr: magically extract key/value pairs from boxy forms

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#21]
monitor a queue

extract all the data you can, including full-page text ocr after line-removal (if this is meaningfully different than the text we pull from the pdfocr layer). we anticipate some attempts at regex-based processing of some of the fields which are not boxy and labelled.

push results into a new json file (childof(original), hidden)
tag original with an alternate view

optionally invoke "next" configured queue

explore ways to quickly detect whether a file or page contains a supported form

it's unclear whether we will always have it segregated or even the first page in a pdf.

**Comment by coler706** [comment]
The before and after line removal is not meaningfully different.
