### ISSUE TITLE
Create Case button inconsistent visibility

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#28]
On the Case List screen, the Create Case button has inconsistent visibility. this bug was carried over from ng implementation.

**Comment by andylippitt** [comment]
Login, see case list with button, View a case, click "Cases" in top nav, return to case-list, button invisible.

**Comment by modderme123** [comment]
This is actually a bug in the cases button in nav, the case button only shows when it knows which organization (provided by the url)
