### ISSUE TITLE
Sync and Log reader pods crashing.

### ISSUE THREAD

**Issue by shanmugarrm** [NYPTI/DEMS#38]
`PS C:\Users\shanmugar.mariappan> kubectl logs -f documents-clients-tools-sync-85ddfbc89c-zjb4q -n test
standard_init_linux.go:190: exec user process caused "no such file or directory"`

`PS C:\Users\shanmugar.mariappan> kubectl logs -f -n test documents-clients-tools-logreader-job-1564770000-kg74v
standard_init_linux.go:190: exec user process caused "no such file or directory"`

**Comment by andylippitt** [comment]
I believe this is caused by a conversion of newline chars from linux LR to windows CRLF at then end of 
https://github.com/NYPTI/DEMS/blob/master/src/Documents.Clients.Tools/dms.sh

Something about our process seems to keep bringing it back.

**Comment by andylippitt** [comment]
this has been resovled by adding to .gitattributes
* text=false
