### ISSUE TITLE
Upgrade existing PDROCR process to Tesseract 4

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#4]
The resultant PDF file should be reassembled from original PDF pages with text added... not rasterized versions of the pages.

**Comment by coler706** [comment]
https://github.com/NYPTI/Documents/pull/251

**Comment by andylippitt** [comment]
we need to review ocrmypdf version and config. 
--force-ocr seems to be causing some file inflation
--redo-ocr seems it might be the right choice, but requiring an update

please also remove the .rb if there's no continued value, and push the ocrmypdf params into the task configuration

**Comment by coler706** [comment]
commit https://github.com/NYPTI/DEMS/commit/023277af9f6605ae39b61990203732a772782000 on master "fix: Update ocrmypdf and use --redo-ocr flag" makes use of the --redo-ocr flag
