### ISSUE TITLE
Defer nav tree UI clear until data is available

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#45]
This seems to be the order of operations

1. Click new path in nav tree
2. nav tree is cleared or collapsed
3. itemQuery returns
4. nav tree is populated.

would like to swap 2 and 3. don't clear until you have the new data or error.  The vast majority of the time, it's the same exact set of data and is unnecessarily flashy.

**Comment by modderme123** [comment]
I'm not able to reproduce this. Is it still an issue?

**Comment by andylippitt** [comment]
seems resolved
