### ISSUE TITLE
Nav Tree not respecting server's "isExpanded"

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#54]
![image](https://user-images.githubusercontent.com/934175/62727067-a1d1ab00-b9e6-11e9-91b3-79dca7f3248e.png)

the json from itemQuery has a property in the paths
"isExpanded": bool

![image](https://user-images.githubusercontent.com/934175/62727154-d34a7680-b9e6-11e9-925d-8bf096358319.png)

I think our only current usage of it is that the server will mark the eDiscovery as expanded if there are any files shared.

**Comment by andylippitt** [comment]
I screwed up my examples. In the screenshot and json, I have the states backwards and not the same path... but the description of the bug is correct. isExpanded is ignored by the client.

**Comment by modderme123** [comment]
The server sends everything as closed. Is this the intended behavior? Maybe the root should be open

**Comment by andylippitt** [comment]
if there are any files shared, it should mark eDiscovery as open

**Comment by andylippitt** [comment]
the root should probably be marked open. seems to have been ignored in the previous client.
