### ISSUE TITLE
eDiscovery Turn Over does nothing

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#56]
![image](https://user-images.githubusercontent.com/934175/62727625-dc881300-b9e7-11e9-8046-1abc3ad258f2.png)

See also #53

**Comment by andylippitt** [comment]
batch request is correct, but it needs to also refresh the itemquery

**Comment by modderme123** [comment]
The server doesn't seem to be proposing a refresh view. Should the client know to do this because of the prompt?

**Comment by andylippitt** [comment]
if it's responsive to the server, please fix it on the server.
please also add to that system a response that would allow a redirect to url in target _top
