### ISSUE TITLE
Mysterious Views isCollapsed behavior

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#66]
![image](https://user-images.githubusercontent.com/934175/62729126-52da4480-b9eb-11e9-88b5-4016285b8393.png)

this value from the server seems to be respected in some conditions... other's seem more complex. Perhaps it's remembering state? 

I'm not sure the values from the server are perfect, but the views are often loading closed, then on return they are loading opened.

**Comment by modderme123** [comment]
I can't seem to get the views to load closed. Is this still an issue?
