### ISSUE TITLE
Search double hit and crash

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#72]
![image](https://user-images.githubusercontent.com/934175/63282098-15dc4080-c27c-11e9-9325-e2829e310065.png)

searched for *

there were two hits to the search endpoint, 200 with clean data
![image](https://user-images.githubusercontent.com/934175/63282303-8aaf7a80-c27c-11e9-839b-780da11e77e5.png)

**Comment by modderme123** [comment]
I'm not able to reproduce this
