### ISSUE TITLE
Modal Cancel/X behavior

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#75]
![image](https://user-images.githubusercontent.com/934175/63949786-e92ce380-ca48-11e9-968b-c2b1661d3d0a.png)

I cannot close the above dialog with the "X" in the top right of the modal. I think it's because cancel is disabled.

**Comment by andylippitt** [comment]
navigate to the "eDiscovery" path and click "add recipient"

**Comment by miami-dade** [comment]
updated cancel and modal close: https://github.com/NYPTI/DEMS/commit/9a25c84bd00da8826549fc7c896264e649573d0e
