### ISSUE TITLE
Clip Editor UI - Muting issue

### ISSUE THREAD

**Issue by jonathancrispino** [NYPTI/DEMS#85]
When trying to mute a segment in a clip, clicking the mute icon more than once causes a UI shift which disables the audio timeline and blocks the "export clip" menu item

![image](https://user-images.githubusercontent.com/33261775/68513749-d0f7f280-0249-11ea-9533-ced4b32d6fe8.png)

**Comment by rebecabkerr** [comment]
I don't see the issue in the current master branch. Is this in another version?

**Comment by rebecabkerr** [comment]
Fixed in branch feature/media-issue
