### ISSUE TITLE
umi2: Upload 2nd chunk fails in dev

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#87]
The second chunk of an upload (> 10MB) has a very long URL in the querystring. this seems to be maxing out whatever webserver is in the nodejs proxy. without the proxy, the upload works.

see if we can extend that with a little config, but no deep dive.

**Comment by miami-dade** [comment]
node changed max header size from 80kb to 8kb in a security release in version 8.x, an environmental variable was introduced in node 10.x but the umi devserver wraps access to the underlying express.js devserver where the variable would be set.
