### ISSUE TITLE
umi2: upload refresh

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#88]
every time a file is uploaded, the folder's view is refreshed.

this is a problem if you upload many small files at once, as it hammers the server on increasingly expensive requests.

limit the frequency of the refreshes during the upload to some maximum and ensure that it's refreshed when the queue is emptied, ensuring it shows the last file uploaded.

**Comment by miami-dade** [comment]
disabled refresh on indiv uploads, refresh fires when queue completes: https://github.com/NYPTI/DEMS/commit/73d01e3da6db8539257bb071f899a00238468c9a

will add configurable option to control this allowing for refresh after X uploads < total
