### ISSUE TITLE
umi2: upload queueing

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#89]
If you upload many files at once (target support for at least 400), all uploads are started and displayed simultaneously.

this needs to be queued, so that a maximum are executed concurrently, and the UI needs to deal with overflow in some functional way.

**Comment by miami-dade** [comment]
updated upload to support maxqueue (currently 200), concurrent uploads (currently 5), as uploads complete pending uploads up to concurrent max transition from waiting to uploading: https://github.com/NYPTI/DEMS/commit/7d0215cbf4ac42f94a3e196071767ea2060fde3a

ui displays queue item rows, can be changed to a summarized view of "X of Y uploading" or other
