### ISSUE TITLE
umi2: upload drag/drop chrome limit

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#90]
As of Chrome 77, this function has been changed to only return the first 100 files, and must be invoked again to get the next batch.
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryReader/readEntries see note about "chrome 77"

	corresponding fix in old angular: https://github.com/NYPTI/DEMS/commit/0c8a7a79a5f4f09ace5cdc878c2c33bae1cc3f3f#diff-b047eaa9ccefe8a43493439f15a837d0
	see second call to dirReader.readEntries(consumeEntries);

**Comment by miami-dade** [comment]
successfully tested 210 files via dragdrop, multiple file select, and folder select folder of 210 files: https://github.com/NYPTI/DEMS/commit/7d0215cbf4ac42f94a3e196071767ea2060fde3a

chrome: Version 78.0.3904.108 (Official Build) (64-bit)
edge: Version 44.18362.449.0
